### ISSUE TITLE
How to reference nugets?

### ISSUE THREAD

**Issue by binki** [jeffkl/RoslynCodeTaskFactory#36]
Hi,

I am wondering what the right way to reference a nuget is. Perhaps it could be mentioned in the documentation. In `<Task><Reference/></Task>`, I don’t know how to get the path to a particular nuget I’m pulling in. If I wanted to reference something like RoslynCodeTaskFactory, I can rely on https://github.com/jeffkl/RoslynCodeTaskFactory/blob/1057defd66ab6c4da1f7d67d510b902d30965402/src/RoslynCodeTaskFactory/RoslynCodeTaskFactory.props and `$(RoslynCodeTaskFactory)`. But most NuGets won’t provide this utility.

Is this something which I should be able to to already or perhaps does this require special NuGet support from RoslynCodeTaskFactory to get it working?

**Comment by jeffkl** [comment]
There is no way to reference stuff that comes from a NuGet package because it would be a lot more involved.  Inline task factories like RoslynCodeTaskFactory run _during_ the build and so they just don't have the ability to restore packages and reference assemblies.  They are really just designed for simple tasks.

If you need to reference stuff beyond what's in NETStandard.Library, you might as well compile a real task library which will run faster and give you the ability to create unit tests.
